# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16UpRnO6ggqnf50UV8v4aKJkq6Ny1m2nx
"""

import pandas as pd
data = "tvmarketing.csv"
adv = pd.read_csv(data)

adv.head()

adv.tail()

import numpy as np

import matplotlib as mp

import sklearn as sk

adv.info()

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize = (10,10))
sns.scatterplot(x = 'TV', y = 'Sales', data = adv)
plt.title('TV vs Sales')
plt.xlabel('TV')
plt.ylabel('Sales')
plt.tight_layout()
plt.show()

